### ISSUE TITLE
[GBA] Hamtaro Rainbow Rescue freeze on Spanish language

### ISSUE THREAD

**Issue by askotx** [mgba-emu/mgba#1098]
Hello, 

On new game in Hamtaro Rainbow Rescue freezes on Spanish language selection intro or later selection menu it freezes, any other language works fine.

Versions 0.6.3: 
-Windows 7 32 bit
-Wii

Version 5.0, 5.1, 6.3, lastest:
-Wii

If you need other info to add, just ask.

Thanks!

**Comment by endrift** [comment]
Can you try a development build?

**Comment by askotx** [comment]
Tried commit 2f33926 and it's showing same behavior on win 7.

Something that I tried yesterday and forget to write: on wii, development build from previous commit didn't boot.

But I've found a workaround, select English language and start a new game, after it started, restart emulator, then select Spanish, it keeps frozen, restart again, so selected language keep enabled

**Comment by JMC47** [comment]
Can confirm this happens in latest nightly builds in Windows 10.

**Comment by endrift** [comment]
Can also confirm.

**Comment by benderscruffy** [comment]
still happens on the latest dev version
works on real hardware
![hamtaro](https://user-images.githubusercontent.com/2696404/60379429-fa676d00-9a64-11e9-9317-82d5519f0912.PNG)

**Comment by endrift** [comment]
This seems to be fixed in latest dev builds; please confirm.

**Comment by benderscruffy** [comment]
yep it is fixed
can be closed
![hamster](https://user-images.githubusercontent.com/2696404/73236094-1a623900-41cc-11ea-9383-f10294977cad.PNG)

**Comment by profi200** [comment]
When testing games i stumbled upon this bug. Happens with both Spanish and German language. Unless the bug fix isn't included in version 0.8.3 yet this bug is back. Log is getting filled with lots of these errors when selecting German:

> [GAME ERROR] GBA Memory:	Bad memory Load32: 0x000D0043
> [GAME ERROR] GBA Memory:	Bad memory Load8: 0x4079407e
