### ISSUE TITLE
Fast-forward no longer works

### ISSUE THREAD

**Issue by guineawheek** [mgba-emu/mgba#117]
When TAB is held down and fast-forward speed is to anything but unbounded, simply frame-skips at normal speed while spamming the console with buffer underflow messages.

When fast-forward speed is unbounded, little to no effect can be seen when TAB is held.

[edit] I am using Ubuntu 15.04 on Intel HD Graphics 4000, OpenGL ES 3.0 Mesa 10.5.9

**Comment by endrift** [comment]
Do you have sync to video enabled?

**Comment by guineawheek** [comment]
I didn't, but having sync to video or sync to audio enabled or disabled
appears to have no effect on the fast-forward speed.

Additionally, the console is flooded with "Got a buffer underflow!"
messages when fast-forward is active.

**Comment by endrift** [comment]
That message means that alsa isn't getting enough samples. Something is screwing with the speed in mGBA, but it doesn't reproduce locally for me.

**Comment by tony971** [comment]
Fast-forward isn't working for me, either. I don't get the error spam but fast forwarding only makes the audio choppy. It doesn't work syncing to audio or video.

**Comment by tony971** [comment]
The faster the desired speed, the more high-pitched and choppy the audio becomes but no speedup actually takes place.

**Comment by endrift** [comment]
I'm actually able to reproduce this on Linux now, I think the original issue was caused by 534c9ca8f87ebf948404c6ad514c99e2deb1bac1. But I'm not sure how to fix it :(

**Comment by purpasmart96** [comment]
You could just temporarily disable double buffering while the user is fast forwarding. Or is it more complex than that?

**Comment by endrift** [comment]
I tried something like that already, and it started crashing deep in Qt.

**Comment by endrift** [comment]
I _believe_ this is fixed in 34d0dff2d670f7a1b282d848d290e3c1c3990f4f. @tony971, @guineawheek, please verify in tomorrow's build.

**Comment by tony971** [comment]
Well you're touching in the right code but not quite fixed yet. It still has the high-pitched, choppy audio playing at 60fps, but now will have individual bursts of fast forward. almost like tapping the fast forward button repeatedly.

**Comment by guineawheek** [comment]
It's better over here with a freshly compiled build; fast-forwarding is fixed, however at first, games play slowly with choppy audio, which is only fixed by fast-forwarding at least once. After that games will run at normal speeds just fine.

Great work on this emulator, by the way, it's the best one I've seen out there.

**Comment by tony971** [comment]
I have an Nvidia GTX 660 with stock settings. My driver is up to date, as well.

**Comment by endrift** [comment]
Bumping to 0.4.0 because the issue affecting 0.3.1 was fixed.

**Comment by karasuhebi** [comment]
Works fine for me, for what it's worth. Have you guys tried a fresh config? Create a portable.ini file and try fast-forward again.

OS: Windows 8.1 Pro

**Comment by tony971** [comment]
Doesn't work with a fresh config. Windows 10 Pro

**Comment by guineawheek** [comment]
Does not seem to be a problem on Windows builds for me; however on Linux occasionally there will be a one second freeze in emulation which does not occur while fast-forwarding.

**Comment by endrift** [comment]
Is this still an issue?

**Comment by tony971** [comment]
It's not an issue on my laptop but I'll have to wait until tomorrow to check on the original computer having issues.

**Comment by tony971** [comment]
This can be marked resolved AFAIK.

**Comment by endrift** [comment]
I'd like to hear back from @guineawheek before closing this.

**Comment by guineawheek** [comment]
No issues recently regarding this. In the time this was opened and today,
there were many graphics commits that appear to have solved the issue
somewhere in there. Feel free to close this, as it's likely no longer
reflective of the current code base and my experience.

This is the best GBA emulator I've seen, especially in regards to its
cross-platform compatibility. It's constantly improving all the time, and I
love seeing this project grow.

Keep up the good work.
