### ISSUE TITLE
Eeprom in game save fails to load (RetroArch)

### ISSUE THREAD

**Issue by eerie-king** [mgba-emu/mgba#1251]
## Description

Copied from libretro/mgba#131

Emulation of eeprom save game (Boktai in this specific case) plays, is able to save, etc. but if you exit the game and return, you are unable to load the save and returns you to a wiped load screen. If exited to title screen, and load screen re-entered, save is still present, but has same result of failed load.

Issue encountered first with mGBA, but encountered with other GBA cores as well. Attempted to use Retroarch 1.7.3 and game save/load works normally, but if old core is moved to current build of retroarch 1.7.5 the failed load result remains.

Included .srm file used.

### Expected behavior

Expected behavior would be for the eeprom save to be able to load while in retroarch normally to resume play.

### Actual behavior

eeprom save fails to load when selected and then appears to wipe data, only for it to remain if load screen re-entered.

### Steps to reproduce the bug

1. Save game in eeprom save game (Boktai as example)
2. exit game fully.
3. restart core/game.
4. attempt to load saved game

### Version/Commit

- RetroArch: 1.7.5
- mGBA 0.7-b1 6db8583
- Git version: 826c77d523
- Build date: Oct 2 2018

### Environment information

- OS: Windows 10 Pro - 64 bit
[failed to load .srm file example.zip](https://github.com/mgba-emu/mgba/files/2651345/failed.to.load.srm.file.example.zip)

**Comment by endrift** [comment]
What version of the core are you using? That git version is for RA itself. Given the description this may be a RA bug.

**Comment by eerie-king** [comment]
My apologies! I've updated it. The version of the core is mGBA 0.7-b1 6db8583.
I was under the impression that it was likely a RA bug as well, but had a comment on my posted issue there (libretro/RetroArch#7702) that I may need to post it over here.

**Comment by eerie-king** [comment]
In discussing issue with others, the possibility of the RTC not being enabled in RA came up. Not certain of the possibility but wanted to include.

**Comment by retro-wertz** [comment]
https://github.com/libretro/RetroArch/issues/7702#issuecomment-445096841
> this seems like a core issue, or specifically how save data and size are passed to libretro.
> for this game at least, its suppose to be using 8192 bytes eeprom, but mgba seems to be initializing a 512 bytes save for it hence some bytes are not written when you exit the game (even though after exiting the size becomes 8192 bytes)
> 
> from experience, libretro has to already know the size of save ram to use before *retro_get_memory_data/size() call(which happens after retro_load_game() but anywhere before retro_run()), but that hasn't been the case here.
> 
> A quick way to confirm this is to force retro_get_memory_size() to return a size of 8192 bytes which the game uses (I've thought mGBA already was padding 512/8192 eeprom saves to use 8192 by default)

**Comment by endrift** [comment]
This appears to have been fixed at some point. Please confirm with latest core.

**Comment by retro-wertz** [comment]
nope. its still a problem loading the save file (using mgba-master's cmakefiles and unpatched version Boktai)

![untitled](https://user-images.githubusercontent.com/23315382/50545022-6ac23c80-0c42-11e9-967d-b5fb25e3b87b.png)

**Comment by endrift** [comment]
That's because that save file is genuinely corrupted. Saving again produces an uncorrupted save.

**Comment by retro-wertz** [comment]
thats a newly created savefile

**Comment by endrift** [comment]
I was on the wrong branch, sorry. It seems to work on the 0.7 branch but not on master. I have a fix for Boktai but I'm not sure it works for other games (i.e. games that don't have overrides).

**Comment by eerie-king** [comment]
Can confirm the same result on my end of the save not being able to be loaded with the current core unfortunately.

**Comment by retro-wertz** [comment]
working now with latest commit

thanks.

**Comment by tchukw25** [comment]
Hi, 
I'm having a similar issue with Boktai when trying to open a save and I get "failed loading".
I'm using RetroArch on Android.
Core: 1.15.0 - magna (0.11 -dev 3e349d5)

I'm not sure how to fix the issue

**Comment by tchukw25** [comment]
I see that this is closed but I'm experiencing the same issue with mgba in the Android version of Retroarch. Is there anything that can be done about that? This is the only place I've seen someone experience the same issue.

Retroarch version: 1.19.1
mgba core version: 0.11 -dev 3e349d5
