### ISSUE TITLE
Random Audio Abnormalities

### ISSUE THREAD

**Issue by justbeets** [mgba-emu/mgba#1533]
Playing Pokemon Emerald on the latest version of the emulator on macOS (downloaded today) produces 'boop' sounds on occasion in mostly battle music and sounds. It's inconsistent, but it usually follows the melody of what is supposed to be played

**Comment by endrift** [comment]
Can you see if it happens in development builds too? I fixed a audio channel 4 bug recently that may be related, but probably isn't.

**Comment by justbeets** [comment]
I just tried to load the ROM with the developer version of the macOS and the video would not load. The audio did load though. The audio problem is still present. It's not entirely random. Specific parts of the Pokemon Center music are always boops.

**Comment by teconmoon** [comment]
Hi there, not sure if this is useful information but I experienced the same issue running the Windows x64 version of 0.7.3. This issue is not present in 0.7.2.

I tested the developer build generated today @ 7 PM and the issue appears to be resolved there.

**Comment by RetroEdit** [comment]
Most likely this 2019 issue has been resolved since 0.7.3 since it was reproduced by @teconmoon who said it was fixed in a dev build. If this remains an issue, it could be reopened.
