### ISSUE TITLE
Solar sensor doesn't work on Libretro core

### ISSUE THREAD

**Issue by gary-ts** [mgba-emu/mgba#1584]
Solar sensor doesn't work on Libretro core.
I tested "Boktai - The Sun Is in Your Hand (USA)".
Solar sensor works fine on mGBA-0.7.3-win32 (through wine), 
but it doesn't work on mgba-master-libretro (Linux x64).

**Comment by endrift** [comment]
I think this was fixed downstream recently. If it was, I'll merge that change in. I need to upstream some changes anyway.

**Comment by gary-ts** [comment]
I tested libretro-mgba-master, but it is not fixed yet.
I posted this issue to libretro's Issues.
Thanks.
