### ISSUE TITLE
Bounded fast forward works like unbounded

### ISSUE THREAD

**Issue by jrisi256** [mgba-emu/mgba#1688]
**System Specs**:
Windows 10
mGBA build 0.8.1
Game - Megaman Battle Network 3 - Blue

**Issue**: If I toggle the Fast Forward speed from "Unbounded" to any other value (2x, 3x, 4x, etc.) the fast forward speed acts as if it were still unbounded.

**Issue 2**: If I use the Shift + Tab shortcut to toggle Fast Forward speed on (rather than holding it) AND the fast forward speed is some value other than unbounded (2x, 3x, 4x, etc.) the game will not fast forward. Shift + Tab only results in the game fast forwarding if the speed is unbounded.

**Comment by endrift** [comment]
Issue 2 is #1590, which has been fixed. Not sure about the first one. Try a dev build to see if it's any better.

**Comment by jrisi256** [comment]
Very interesting. Downloading the dev build from 2020 March 1 resolved Issue #2, but it did not resolve issue #1. I'll continue using this dev build and using fast forward toggle rather than fast forward held. Thanks for such a great emulator! :D

**Comment by Zootwem** [comment]
> Issue 1: If I toggle the Fast Forward speed from "Unbounded" to any other value (2x, 3x, 4x, etc.) the fast forward speed (held) acts as if it were still unbounded.

I'm having the same trouble. Held fast forward is unbounded no matter if I change the option.

**Comment by Vortaka** [comment]
Here's a little test I happened to do (version 0.8.3).
When Display driver is set to OpenGL, anything unbounded gives me weird sound but it doesn't go faster...
Display Driver OpenGL unbound works...  (But it's a little too fast for me!)

When Display driver is set to software (QT), it works as it should!  Both ?x and unbounded...

**Comment by shrx** [comment]
Issue is still present in 0.9.3.

**Comment by olavim** [comment]
There is a separate setting for held fast forward speed in Tools -> Settings -> Emulation.

**Comment by aljohnston112** [comment]
Please add that to the emulation menu for easy access for future users. It is bad UX to have two related settings like this in isolation.
