### ISSUE TITLE
Glitched graphics on Final Fantasy I+II

### ISSUE THREAD

**Issue by renecatharsis** [mgba-emu/mgba#1711]
The top three (?) rows of the graphics turn into some glitched state when talking to NPCs in any city of Final Fantasy I on GBA. Cannot be reproduced consistently though, I have to leave and enter town again a couple of times until I get it for sure.
Using OpenGL renderer. Issue doesn't occur when using Qt Software Renderer, unfortunately the emulation seems to be lagging just a tad bit using that one.

Build used: mGBA-0.8.1-win64
OS: Win10 Pro, 64-bit
System specs: Core i7-8750H, GeForce GTX 1060
ROM CRC: 7c9854c6

Please let me know if there's any further settings, system information, savefile etc. information that might help. 

![ff1-glitched-rows](https://user-images.githubusercontent.com/1114906/77857491-06ec4200-71fe-11ea-835a-86d7a33f850e.png)

**Comment by renecatharsis** [comment]
Still happens on mGBA-0.8.2-win64 but less regularly.
See the savestates attached.
[mgba-1711.zip](https://github.com/mgba-emu/mgba/files/4788875/mgba-1711.zip)

With 0.8.2 some really quick screen flickering started to appear.
I've recorded it because I cannot savestate it. Happens bettwen 0:07 - 0:08, 0:11 - 0:12
Video is in the attachement, too.

**Comment by renecatharsis** [comment]
Still happens on mGBA-0.8.3-win64.
I additionally tested it on different scalings to rule out upscaling as an issue. The issue affects both the original scaling/aspect ratio as well as increased scalings like 2x or 4x.

**Comment by endrift** [comment]
I had trouble reproducing this when I tried. I'll try again to get it fixed in 0.9 (assuming you've tried it in a dev build already?)

**Comment by renecatharsis** [comment]
Yes, tested it on previous dev builds and just now on build 6385-453791d.
Glitches still occur. Unfortunately I couldn't use my save states on the dev build. Loading it fails with:
`Jumped to invalid address: E3A03300`

Memory address displayed is consistent on every attempt to load it.

**Comment by endrift** [comment]
Savestates can be flaky like that. I'll look into it, and if possible I'd appreciate making a new savestate. Otherwise I'll try grabbing the savegame out of the state and using that (assuming there is one in there; there isn't always).

**Comment by renecatharsis** [comment]
Gimme a sec, I'll attach new save files plus a save file for the dev build.

**Comment by renecatharsis** [comment]
There you go, save file and save state showing the permanent glitch.
Flickering can still be reproduced by talking to NPCs and skipping through their dialog.
[mgba-1711-dev.zip](https://github.com/mgba-emu/mgba/files/5024591/mgba-1711-dev.zip)

**Comment by endrift** [comment]
I can't reproduce this on Linux/Intel GPU, but I CAN reproduce this on Windows/Nvidia GPU. It may be a driver bug. Will continue to investigate.

**Comment by endrift** [comment]
I think I figured out why I can't reproduce it; it's not an OpenGL bug, it's a bug that doesn't happen if using the official BIOS. This appears to be another manifestation of the same bug in #1823.

**Comment by renecatharsis** [comment]
If there's any more testing I can do or just driver information I can provide feel free to let me know.
Will keep testing on newer dev build every now and then.
