### ISSUE TITLE
 OpenGL/Zelda Minish Cap: Abnormal sprite popping during boss battle

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#1712]
In the first boss battle, if the enemy has half of his body out of the screen, almost all his body disappears. This effect also happens when the boss jumps.

![minishOpenGL-BUG mkv_snapshot_00 01 869](https://user-images.githubusercontent.com/16591467/77960359-75053780-72d8-11ea-8775-b274a3d2892c.jpg)

The bug doesn't affect the software renderer. I only tested the European version.

Save and savestate:
[Save and savestate Zelda minish cap Boss 1.zip](https://github.com/mgba-emu/mgba/files/4405400/Save.and.savestate.Zelda.minish.cap.Boss.1.zip)

Video of the OpenGL renderer and the Software renderer
[Zelda Videos.zip](https://github.com/mgba-emu/mgba/files/4405408/Zelda.Videos.zip)

Specs:
Mgba: Latest win64 build
Windows 10 x64, Nvidia 820M/Intel HD4600

**Comment by angelxd84130** [comment]
Hi, I think the problem has been solved in the last version of 0.9-6160. Would you mind to try it again
![legend-of-zelda-the-the-minish-cap-usa-1](https://user-images.githubusercontent.com/19487525/79058287-f4700080-7c20-11ea-9fb7-3ddbe8ee4083.png)

**Comment by RafaelTrepaUnCarballo** [comment]
No, it still happens in the last build

Are you sure you enabled the OpenGL HD mode?

**Comment by angelxd84130** [comment]
Well..could you share where you download the rom? so I can test again. Thanks

**Comment by endrift** [comment]
Asking for ROMs is not allowed

**Comment by angelxd84130** [comment]
Sorry I didn't know that. 
@RafaelTrepaUnCarballo, I think to try other sources might be helpful :)
