### ISSUE TITLE
Game Boy Camera not working

### ISSUE THREAD

**Issue by LeakySponge** [mgba-emu/mgba#2256]
After putting in the camera driver to Qt Multimedia and the camera to the built in webcam I have on my laptop, it just says "NO CAM" with a X mark. I don't know what to do about this.

**Comment by endrift** [comment]
This was probably fixed in e87f7b7b6885c63ad35ac4f6d0cd4d74e1d36d70. Please retest with newest mGBA.

**Comment by ljcool2006** [comment]
This still doesn't work. The camera that I'm using is OBS Virtual Camera.
