### ISSUE TITLE
[PS Vita] Cannot compile against docker

### ISSUE THREAD

**Issue by feraligatr** [mgba-emu/mgba#2289]
➜  mgba git:(f6d5f51d2) docker run --rm -t -v $PWD:/home/mgba/src mgba/vita
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Check for working C compiler: /opt/vitasdk/bin/arm-vita-eabi-gcc
-- Check for working C compiler: /opt/vitasdk/bin/arm-vita-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/vitasdk/bin/arm-vita-eabi-g++
-- Check for working CXX compiler: /opt/vitasdk/bin/arm-vita-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing:  PKG_CONFIG_EXECUTABLE) 
-- The ASM compiler identification is GNU
-- Found assembler: /opt/vitasdk/bin/arm-vita-eabi-gcc
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strlcpy
-- Looking for strlcpy - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for include file xlocale.h
-- Looking for include file xlocale.h - not found
-- Looking for chmod
-- Looking for chmod - not found
-- Looking for umask
-- Looking for umask - not found
-- Checking for one of the modules 'libavcodec'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libavcodec missing for feature USE_FFMPEG.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:515 (find_feature)

-- Checking for one of the modules 'minizip'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module minizip missing for feature USE_MINIZIP.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:518 (find_feature)

-- Checking for one of the modules 'epoxy'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module epoxy missing for feature USE_EPOXY.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:521 (find_feature)

-- Checking for one of the modules 'libelf'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libelf missing for feature USE_ELF.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:524 (find_feature)

-- Build type: Release
-- Platforms:
-- 	Game Boy Advance: ON
-- 	Game Boy: ON
-- Features:
-- 	Debuggers: OFF
-- 	CLI debugger: OFF
-- 	GDB stub: OFF
-- 	GIF/Video recording: OFF
-- 	Screenshot/advanced savestate support: ON
-- 	ZIP support: libzip
-- 	7-Zip support: ON
-- 	SQLite3 game database: OFF
-- 	ELF loading support: OFF
-- 	Discord Rich Presence support: OFF
-- 	OpenGL support: OFF
-- Frontends:
-- 	Qt: OFF
-- 	SDL (): OFF
-- 	Profiling: OFF
-- 	Test harness: OFF
-- 	Test suite: OFF
-- 	Video test suite: OFF
-- 	Python bindings: OFF
-- 	Examples: OFF
-- Cores:
-- 	Libretro core: OFF
-- Libraries:
-- 	Static: ON
-- 	Shared: OFF
-- Configuring done
CMake Error at src/platform/psp2/CMakeLists.txt:39 (add_executable):
  Target "mgba.elf" links to target "BZip2::BZip2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/platform/psp2/CMakeLists.txt:39 (add_executable):
  Target "mgba.elf" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/platform/psp2/CMakeLists.txt:39 (add_executable):
  Target "mgba.elf" links to target "OpenSSL::Crypto" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at CMakeLists.txt:892 (add_library):
  Target "mgba" links to target "BZip2::BZip2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?

CMake Error at CMakeLists.txt:892 (add_library):
  Target "mgba" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at CMakeLists.txt:892 (add_library):
  Target "mgba" links to target "OpenSSL::Crypto" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/platform/psp2/CMakeLists.txt:39 (add_executable):
  Target "mgba.elf" links to target "BZip2::BZip2" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/platform/psp2/CMakeLists.txt:39 (add_executable):
  Target "mgba.elf" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

CMake Error at src/platform/psp2/CMakeLists.txt:39 (add_executable):
  Target "mgba.elf" links to target "OpenSSL::Crypto" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /home/mgba/src/build-vita

**Comment by endrift** [comment]
I believe this is fixed now. Please retest.

**Comment by feraligatr** [comment]
➜  mgba git:(f6d5f51d2) docker run --rm -t -v $PWD:/home/mgba/src mgba/vita
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Check for working C compiler: /opt/vitasdk/bin/arm-vita-eabi-gcc
-- Check for working C compiler: /opt/vitasdk/bin/arm-vita-eabi-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/vitasdk/bin/arm-vita-eabi-g++
-- Check for working CXX compiler: /opt/vitasdk/bin/arm-vita-eabi-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- The ASM compiler identification is GNU
-- Found assembler: /opt/vitasdk/bin/arm-vita-eabi-gcc
-- Looking for strdup
-- Looking for strdup - found
-- Looking for strndup
-- Looking for strndup - found
-- Looking for strlcpy
-- Looking for strlcpy - found
-- Looking for vasprintf
-- Looking for vasprintf - found
-- Looking for include file xlocale.h
-- Looking for include file xlocale.h - not found
-- Looking for chmod
-- Looking for chmod - not found
-- Looking for umask
-- Looking for umask - not found
-- Checking for one of the modules 'libavcodec'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libavcodec missing for feature USE_FFMPEG.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:515 (find_feature)


-- Checking for one of the modules 'minizip'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module minizip missing for feature USE_MINIZIP.  Feature
  disabled.
Call Stack (most recent call first):
  CMakeLists.txt:518 (find_feature)


-- Checking for one of the modules 'libzip'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libzip missing for feature USE_LIBZIP.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:520 (find_feature)


-- Checking for one of the modules 'epoxy'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module epoxy missing for feature USE_EPOXY.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:521 (find_feature)


-- Checking for one of the modules 'libelf'
CMake Warning at src/platform/cmake/FindFeature.cmake:51 (message):
  Requested module libelf missing for feature USE_ELF.  Feature disabled.
Call Stack (most recent call first):
  CMakeLists.txt:524 (find_feature)


-- Build type: Release
-- Platforms:
-- 	Game Boy Advance: ON
-- 	Game Boy: ON
-- Features:
-- 	Debuggers: OFF
-- 	CLI debugger: OFF
-- 	GDB stub: OFF
-- 	GIF/Video recording: OFF
-- 	Screenshot/advanced savestate support: ON
-- 	ZIP support: minizip (included)
-- 	7-Zip support: ON
-- 	SQLite3 game database: OFF
-- 	ELF loading support: OFF
-- 	Discord Rich Presence support: OFF
-- 	OpenGL support: OFF
-- Frontends:
-- 	Qt: OFF
-- 	SDL (): OFF
-- 	Profiling: OFF
-- 	Test harness: OFF
-- 	Test suite: OFF
-- 	Video test suite: OFF
-- 	Python bindings: OFF
-- 	Examples: OFF
-- Cores:
-- 	Libretro core: OFF
-- Libraries:
-- 	Static: ON
-- 	Shared: OFF
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mgba/src/build-vita
Scanning dependencies of target mgba-version-info
[  0%] Built target mgba-version-info
Scanning dependencies of target mgba
[  0%] Building C object CMakeFiles/mgba.dir/src/core/bitmap-cache.c.obj
[  1%] Building C object CMakeFiles/mgba.dir/src/core/cache-set.c.obj
[  2%] Building C object CMakeFiles/mgba.dir/src/core/cheats.c.obj
/home/mgba/src/src/core/cheats.c: In function 'mCheatSetInit':
/home/mgba/src/src/core/cheats.c:201:15: error: implicit declaration of function 'strdup'; did you mean 'strcmp'? [-Werror=implicit-function-declaration]
  201 |   set->name = strdup(name);
      |               ^~~~~~
      |               strcmp
/home/mgba/src/src/core/cheats.c:201:13: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  201 |   set->name = strdup(name);
      |             ^
/home/mgba/src/src/core/cheats.c: In function 'mCheatSetRename':
/home/mgba/src/src/core/cheats.c:231:13: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  231 |   set->name = strdup(name);
      |             ^
/home/mgba/src/src/core/cheats.c: In function 'mCheatAddLine':
/home/mgba/src/src/core/cheats.c:239:33: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  239 |  *StringListAppend(&set->lines) = strdup(line);
      |                                 ^
/home/mgba/src/src/core/cheats.c: In function 'mCheatParseFile':
/home/mgba/src/src/core/cheats.c:321:35: warning: assignment to 'char *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  321 |    *StringListAppend(&directives) = strdup(&cheat[i]);
      |                                   ^
In file included from /home/mgba/src/include/mgba-util/common.h:23,
                 from /home/mgba/src/include/mgba/core/cheats.h:9,
                 from /home/mgba/src/src/core/cheats.c:6:
/home/mgba/src/src/core/cheats.c: In function 'mCheatParseLibretroFile':
/home/mgba/src/src/core/cheats.c:396:39: warning: array subscript has type 'char' [-Wchar-subscripts]
  396 |     if (end[0] != '\0' && !isspace(end[0])) {
      |                                    ~~~^~~
cc1: some warnings being treated as errors
make[2]: *** [CMakeFiles/mgba.dir/build.make:89: CMakeFiles/mgba.dir/src/core/cheats.c.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:291: CMakeFiles/mgba.dir/all] Error 2
make: *** [Makefile:152: all] Error 2

**Comment by feraligatr** [comment]
1. I still have problem with strdup on tag 0.9.2. (cannot compile on master either)
2. Can I enable all features with docker build?

**Comment by endrift** [comment]
1. You need to delete the build directory first, as some of this stuff is cached. Further, it won't build with 0.9.2 anymore since source changes are needed and I'm not re-tagging a release. Use master or the 0.9 branch.
2. What do you mean by "all features"...? Most of those things aren't even supported, much less exposed, on those platforms, e.g. video recording. The only one that actually is usable that's missing is libelf, which doesn't even affect commercial games.

**Comment by feraligatr** [comment]
Thank you very much! It works on master branch. Sorry I forgot to pull master when I tried with it.
Will libelf be available on docker?

**Comment by endrift** [comment]
The Vita version does not currently support libelf. Those checks are there regardless of if the platform in question supports those features, as the failures are simply warnings that can be ignored.
