### ISSUE TITLE
[Wii] Erratic movements with the left stick of the Wii Classic Controller 

### ISSUE THREAD

**Issue by RafaelTrepaUnCarballo** [mgba-emu/mgba#298]
I noticed the characters move strangely when I'm using the left stick of the classic controller. Neither the gamecube pad nor the Digital Pad of any pad suffer this problem.

Description of the bug: When I'm moving down and I change the direction to up the games still think I'm moving down or it alternates up and down randomly. 

This affects any game I checked (for example Golden Sun 2, Mario Golf...).
I think it only affects the Y axis, but I'm not completely sure.

**Comment by endrift** [comment]
Unfortunately I don't have a classic controller to debug this issue with.

**Comment by endrift** [comment]
Does this still reproduce? I merged some changes into libogc that were supposed to fix this.

**Comment by RafaelTrepaUnCarballo** [comment]
It's still there.

**Comment by endrift** [comment]
I've just pushed some fixes for classic controller handling, can you check with the latest build in a bit?

**Comment by RafaelTrepaUnCarballo** [comment]
No, it's still broken. Although I noticed something that might help you to fix the bug:

The problem affects mostly UP and DOWN (Y axis) and only when you tilt the joystick to the maximum.
If you tilt it a 80% everything works as intended.

I have no idea of how Wii hardware and software works, but I suspect it could be caused by oddities in the way the axis of the classic controller works...

maybe the values of the axis Y grow bigger than the variable limit, overflowing it and becoming negative? (that would explain why you start going down when you tilt up to the limit)

Just a theory, better ask Dolphin devs for it.

**Comment by endrift** [comment]
This might be fixed now, please retest.

**Comment by RafaelTrepaUnCarballo** [comment]
It is fixed now.
