### ISSUE TITLE
NS Pro Controller has no rumble effect

### ISSUE THREAD

**Issue by Hexaae** [mgba-emu/mgba#3147]
**mGBA 0.11-8325-49d9b70e6**
Win 11 23H3, NVidia GTX 1070 8GB, i7-8750H 32GB RAM

Bought an hybrid modern controller perfectly seen as an original XBox One BT controller or NS Pro Controller.
With XBox One controller mode rumble works fine (a bit lite maybe... wish there was a Force slider #2797 ...) for games like Drill Dozer for GBA, but with NS Pro Controller rumble is simply absent.

![image](https://github.com/mgba-emu/mgba/assets/8591462/6fc8b73d-126e-4e82-92c6-99a4d8dfea4e)

Gyro works with Kirby Tilt 'n Tumble.

**Comment by Hexaae** [comment]
Still the same with DEV 8331-d8ab5529a

**Comment by endrift** [comment]
I pushed a change that might have fixed this. Please test the latest build.

**Comment by Hexaae** [comment]
8332-c8c9fcb66 still no rumble with NS Pro Controller (only, XBox Controller rumbles)😭

**Comment by Hexaae** [comment]
Currently using 0.11-8442. NS Pro Controller (only) still missing rumble effect.

**Comment by endrift** [comment]
So I've confirmed on my end that it _does_ work on latest Windows build with my Pro Controller, both wired and over Bluetooth. Is the firmware on your Pro Controller up to date? I might need to figure out how to collect logs from SDL.

**Comment by Hexaae** [comment]
It's a compatible controller (EasySMX X10), but it does work everywhere including Steam Input (SDL2) with rumble...

**Comment by Hexaae** [comment]
No, still doesn't work with Drill Dozer

**Comment by endrift** [comment]
This model? https://www.easysmx.com/products/easysmx-x10-game-controller-with-mechanical-buttons-and-hall-joysticks

I'd probably need to actually buy one to debug this. It might be possible to give you some commands to run to get some logs but I would need to figure that out.

**Comment by endrift** [comment]
[testgamecontroller.zip](https://github.com/mgba-emu/mgba/files/15446232/testgamecontroller.zip)

Here's a copy of the test utility that comes with SDL built against the same version of SDL in mGBA. It should vibrate with one motor when you hit ZR and the other when you hit ZL. Do they both work in Switch mode?

**Comment by Hexaae** [comment]
ZL works (but with a long delay after you press it and 1 sec later it rumbles), ZR does nothing...

**Comment by endrift** [comment]
I have gotten an X10 controller now and can reproduce the ZL working but ZR not. This may be an issue with the controller itself, which is unfortunate considering NS mode has a gyro and therefore would be good for WarioWare,  but XInput mode doesn't.

**Comment by Hexaae** [comment]
Sigh... from a non-programmer POV all I can say is that it works flawlessly including rumble with Steam (still SDL2) in games like Horizon Zero Dawn, and CEMU, Yuzu... Strange it doesn't with mgba only :(

**Comment by Hexaae** [comment]
@endrift 
Did you update firmware of X10 BTW? Here is official latest fw update: https://drive.google.com/file/d/1eWgEnhekRx1xJMW-s1QxBJ98eDP4pGLr/view from [Discord channel of EasySMX ](https://discord.com/channels/966953732015276032/1072080260260171899)

**Comment by endrift** [comment]
Just updated. No change. I'm going to look into fixing SDL on my end so all inputs to rumble work, and not just some.

**Comment by endrift** [comment]
Unfortunately using a real Switch I've verified that the controller does not parse the rumble data properly and thus only rumbles on a seemingly random subset of inputs. This is definitely a bug with the controller firmware.

**Comment by Hexaae** [comment]
Thanks for checking this out... Will report the issue in the support channel of EasySMX... 🤞🏻
