### ISSUE TITLE
[Vita] DBZ Supersonic Warriors Camera Issues

### ISSUE THREAD

**Issue by OTFree** [mgba-emu/mgba#336]
First off, let me start with much needed positive feedback; the latest nightly revision of mGBA (Vita) overall runs extremely well now (with most titles I try running at full speed with no lag/stutter/audio issues, and that's frameskip disabled!). So big thanks to the huge increase in performance in a short time, we can expect great things to continue to come from this emulator :)

Now here's the weird issue I encountered, "Dragon Ball Z Supersonic Warriors" runs perfectly (in terms of sound, speed and graphically), but the in game camera is extremely buggy and non functional, making the game virtually unplayable. Not sure what could be causing it, but because of it, the movement is inverted (the characters are facing backwards) and the camera doesn't properly focus or follow the sprites on screen (even drastically zooming out at times for no reason).

I hope this gets fixed soon because otherwise, the game seems to be running amazing if this bug wasn't present. Seems to be a rom specific issue though!

**Comment by endrift** [comment]
Please try this with the official BIOS. This sounds like an HLE BIOS bug.

**Comment by OTFree** [comment]
Thank you! That seems to have fixed it. The game has some slowdown now, but
I far prefer that over game breaking glitches!

**Comment by endrift** [comment]
Awesome, I'll try to fix the HLE BIOS soon. It's probably the same bug as #333.

**Comment by endrift** [comment]
Should be fixed in 6867400ca875277929f8aec1964c99d85cb0e1a9 without the BIOS. Let me know.

**Comment by OTFree** [comment]
Thank you for the quick response as always! Using the newest nightly build
now. Disabled "use bios", reset, and launched the game. Unfortunately, the
glitch is still happening during battle, but seems less frequent :/

**Comment by endrift** [comment]
I just committed that fix; it's not in a nightly yet. It will be tomorrow night, but I'll probably post it on twitter before then.

**Comment by OTFree** [comment]
Ahhh, okay. Sorry about that, so I should wait until tomorrow's nightly
then?

**Comment by OTFree** [comment]
Can confirm this problem is fixed with latest nightlies. Thank you so much!
