### ISSUE TITLE
Latest mGBA Git (2016/09/01) on EmuCR has various issues

### ISSUE THREAD

**Issue by Lerianis** [mgba-emu/mgba#372]
To lay out the issues I will be going in numerical order:

1. When games are in .7z archives, unless you press 'fast-forward' the games start out very very slow. 15 fps at most. As soon as you press 'fast-forward' even if it is only for a second however something in the emulator logic clicks and the game is back to the speed (60fps on my system) that I expected it to be at.

2. This version has an issue where it is not properly reading Save States and Save Data from previous versions. It is also making it's own Save States and Save Data for games with nonsensical random character names like ��T.ss1 and ��T.sav for Metroid Fusion respectively.
If I rename the Save Data temporarily to those nonsensical names, the emulator reads the Save Data and Save States properly.

3. There is a sudden, strange slowdown in various games after about 30-45 minutes of playing them on my PC's. I have tested on an Acer E5-571-5552, a Gateway P-7811FX, a Toshiba A135-S4467, and an HP H8 1010T desktop PC and all of them have this same issue.
I have tried turning on logs (all the checkboxes checked) and there is no error message coming up when the issue happens.

**Comment by endrift** [comment]
I think I have a fix for 2 shortly. The others will take more testing.

**Comment by endrift** [comment]
I cannot reproduce 1.

**Comment by endrift** [comment]
I also cannot reproduce 3.

**Comment by Lerianis** [comment]
Okay, I'll try to figure out if it is an issue with my setup on my computers then.

**Comment by endrift** [comment]
Can I get more information about which of the various games you were using to reproduce 3? I wonder if it's game-specific.

As for 1, was this using the "load from archive" feature, or just loading the 7z directly?

**Comment by Lerianis** [comment]
Issue 1 is loading the 7z directly, not using the "Load From Archive" option. Honestly I could never get the "Load from Archive" option to work with 7z archives, it kept on telling me that there was no game in the 7z file that I loaded so I finally gave up trying to use "Load From Archive".

3 was using Metroid Fusion, Metroid Zero Mission, American Dragon Jake Long: Rise of the Huntsclan!, and Dragon Ball Z: Buu's Fury that I am absolutely sure the slowdown happened with. Legend of Zelda: The Minish Cap was one that I thought the slowdown happened up but I am not sure since it was a few weeks ago and I finished the game, not going back to it since.

Though, I just experienced the slowdown in Issue 3 last night and I am thinking it is something with my computers now.
Disk access was going up to 100% in Task Manager due to Windows Update doing something with another application doing a lot of hard drive access and that is when the slowdown occurred last night.
Might want to mark that as a problem on my end until further notice.

**Comment by endrift** [comment]
Can you recheck 1 with a newer build? I fixed some archive load stuff, so see if it all works now.

**Comment by Lerianis** [comment]
Issue 1 is still present on the mGBA Git (2016/09/16) build on EmuCR.com. It still has that "Starting out at less than 20 fps (now it is bobbling instead of staying at 15fps permanently until you do the semi-fix I noted in the first post)" where pressing the fast-forward button fixes it.

**Comment by endrift** [comment]
Try an official build from the development section on the downloads page at mGBA.io

There's zero reason to download a build from emucr since I build all the platforms myself nightly.

**Comment by Lerianis** [comment]
Well dang. It must have been something that EmuCR was doing with the build compilation because with the actual build from your website, the issue is non-existent. Totally gone.

Sorry to waste your time with this.

**Comment by endrift** [comment]
Guess I should put out a PSA to avoid the EmuCR builds :/
