### ISSUE TITLE
Loading recent game from archive loads different ROM

### ISSUE THREAD

**Issue by DarkD** [mgba-emu/mgba#413]
When loading game from "Recent" menu it loads not the very same ROM from archive, but very first.
mGBA 0.6-4020 same goes for 0.5.0.
Should be remembered which ROM was chosen in "Open in archive..." window or at least call that window before loading.
Thanks!

**Comment by endrift** [comment]
Yeah, this was never implemented due to the fact that the MRU only holds one piece of path information, and I'd need to save two (path to archive and path in archive) for this to be feasible.

**Comment by endrift** [comment]
I think this is fixed now. Can you check?

**Comment by DarkD** [comment]
No, it's not fixed. Grabbed version 0.6-4403-35b5626 and when loading is finished all fields are blank, but you can select item(number of blank items are same as ROMs in archive) and "load" it, though nothing happens after that. If you choose "Load ROM" instead of "Load ROM in archive" it loads first ROM in archive. "Recent" works with that option.
Last vesion I had was r.0.6-4372-40ff1ea and memory fails me, I remember playing Zelda - Minish Cap nicely on it, but now, when I'm checking it doesn't loads from "Recent" either. At least it opens archives like it should... Sadly I don't have any version between those to check.

**Comment by DarkD** [comment]
Just wanted to let you know that on 0.6-4559 it works finely and issue should be closed. Well done!

**Comment by endrift** [comment]
This was probably fixed by merging @waddlesplash's library PR.
