### ISSUE TITLE
MGBA nightly January 12 - game audio can become incorrect upon loading state.

### ISSUE THREAD

**Issue by ghost** [mgba-emu/mgba#496]
This doesn't seem to last too long (the next time the music loops/sound is loaded, I think), but I've noticed that audio can have oddities when reloading a quickstate. I'm pretty sure this is only for 8-bit noise and wave channels and such, as sampled sounds seem to work right.

Here's 2 seven second samples of audio, the 1st one being correct, an the second as a result of loading a state.

[mgbaaudiomessupexample.zip](https://github.com/mgba-emu/mgba/files/705589/mgbaaudiomessupexample.zip)

**Comment by endrift** [comment]
I take it this is from Mother 1+2? Can you upload a savestate?

**Comment by TheGoatManfan** [comment]
Correct. Accidentally found it when I was fooling around with different games to see different results. I couldn't get this audio bug working when using hotkeys. Using F1 made the audio correct. But going to file > Quick load > State 1 caused this. I also have the program set to NOT pause when inactive, if that causes any issues.

[savestate1.zip](https://github.com/mgba-emu/mgba/files/705684/savestate1.zip)

**Comment by Mushman** [comment]
I am able to consistently reproduce this bug in Super Mario Bros. Deluxe. Here are two save states where you can reliably test this yourself. The first is the beginning of a new game on 1-1. From there, pausing the game, creating a save state (I used the `Shift + F1` shortcut), and then reloading that state (also using `F1`) will cause the issue. The second state should demonstrate the error upon load, even if you load it immediately after resetting.

[mGBA #496 SMB Deluxe.zip](https://github.com/mgba-emu/mgba/files/3749767/mGBA.496.SMB.Deluxe.zip)

**Comment by endrift** [comment]
I believe this is fixed in master, at least as described by @Mushman. I could reproduce a small issue when I was testing earlier (using fresh savestates), but it's fixed as of latest master.

**Comment by J-Nagle** [comment]
This still happens. I've made a video reproducing the bug using the latest master.

[MGBA #496 Audio Load State - 0.9-6405-54978722 (Super Mario Bros. Deluxe).zip](https://github.com/mgba-emu/mgba/files/5054559/MGBA.496.Audio.Load.State.-.0.9-6405-54978722.Super.Mario.Bros.Deluxe.zip)

**Comment by Mushman** [comment]
This still happens. I've made a video reproducing the bug using the latest master.

[MGBA #496 Audio Load State - 0.9-6405-54978722 (Super Mario Bros. Deluxe).zip](https://github.com/mgba-emu/mgba/files/5054569/MGBA.496.Audio.Load.State.-.0.9-6405-54978722.Super.Mario.Bros.Deluxe.zip)

**Comment by endrift** [comment]
Nice opsec. Did you make sure to do it from a fresh state? Old states may have the issues embedded in them.

**Comment by Mushman** [comment]
> Nice opsec.

):

> Did you make sure to do it from a fresh state? Old states may have the issues embedded in them.

Yes. I show that in the video.

**Comment by endrift** [comment]
I see you used 6405 (54978722). The commits in question happened after that. However, the buildbot hasn't caught up yet. Please wait half an hour or so and try again with a newer build (6409 7652fe9f7ae13b4e3d5b29e0ebf869d7503b22cc or newer).

Also, don't worry I deleted the evidence :P

**Comment by Mushman** [comment]
Ah, sorry. I neglected to check if the dev version was actually the latest master. Will retest. Cheers mate.

**Comment by endrift** [comment]
Guess I was premature reopening the issue. Thanks for retesting so promptly!

**Comment by Mushman** [comment]
Just did a little more testing with Build 6411. Turns out it's still reproducible if the triangle channel was playing before the users loads state. This table shows the behaviour.

| Triangle Channel | Before State Load | After State Load | MGBA 0.8.3 After State Load | MGBA Build 6411 After State Load |
| --- | --- | --- | --- | --- |
| Playing | ✅ | ❌ | ✅ | ✅ |
| Silent | ❌ | ❌ | ✅ | ❌ |

**Comment by RetroEdit** [comment]
Premature on re-closing after re-opening before the final test results came, eh? (sorry for the off-topic comment)

**Comment by endrift** [comment]
I found one potential issue immediately. Let me know if my fix was enough (it probably wasn't).

**Comment by Mushman** [comment]
It wasn't, unfortunately. Build 6146 behaviours like Build 6411.

**Comment by endrift** [comment]
I am no longer able to reproduce this. Please confirm if it still reproduces.

**Comment by Mushman** [comment]
My tests confirm that the you've fixed the issue. Audio doesn't glitch anymore when loading states on 0.9.0 and the latest development build 6951. Thanks a lot!
