### ISSUE TITLE
Software breakpoints don't do anything if there aren't any hardware breakpoints

### ISSUE THREAD

**Issue by jeremyherbert** [mgba-emu/mgba#550]
Hi,

`ARMDebuggerCheckBreakpoints`@`/src/arm/debugger/debugger.c:35` checks to see if there are any hardware breakpoints pending, and then returns immediately if there are none. This causes it to not check if any software breakpoints are pending. 

I'm trying to work out a patch to fix this, but I'm struggling to understand the difference between hardware and software breakpoints in this emulator. Why are both needed? What is the difference between them? In my understanding, the only reason software breakpoints exist in debuggers is because on real hardware you can't have an unlimited number of breakpoints. But in the case of an emulator, this isn't an issue, because we are running a simulation of the CPU anyway, so we can break it at any point (PC address/memory access/register change, etc).

Thanks

**Comment by endrift** [comment]
Have you actually verified that this is broken by testing it instead of looking at the source? Because software breakpoints go through an entirely different codepath. They insert BKPT instructions into memory, which then cause the emulation to trap when they're hit. This bubbles up into GBABreakpoint, which does appear to enter the debugger. This codepath never even hits ARMDebuggerCheckBreakpoints.

The reason these are separate is because hardware breakpoints slow down the emulation. It has to check EVERY instruction if it's hit a breakpoint. There are ways to optimize this that I haven't implemented (e.g. a bloom filter), but it will never be as fast as simply not checking every instruction. That's where the software breakpoints come in: we don't have to check for the breakpoints unless one actually gets hit. But there are disadvantages too: the memory can be overwritten or read, so it isn't a pure simulation anymore. Quite often, however, it can suffice.

**Comment by jeremyherbert** [comment]
Yes, I have verified this at runtime. My software break points do not appear to trigger.

**Comment by jeremyherbert** [comment]
Also thank you for the explanation about the difference between the two; that makes sense.

**Comment by endrift** [comment]
Weird, they work fine for me with GDB. There's a bug that can cause it to crash on ROM addresses that I just fixed (but haven't pushed yet), but they're definitely getting hit normally.

**Comment by jeremyherbert** [comment]
Ok thanks for the confirmation. I'll keep digging on this after work today.

**Comment by jeremyherbert** [comment]
Well I've been playing with this for a bit, but I still can't get it to go. Might be some issue with my setup, but I will report my progress here anyway as sort of notes to myself. I'm using IDA 6.8 as the debugger.

First, I set a software breakpoint at address 0x6C. This is only a few instructions into execution from reset. When connecting IDA, the following messages are sent to mgba:

`
got message: !#21
got message: ?#3f
got message: qfThreadInfo#bb
got message: qsThreadInfo#c8
got message: qC#b4
got message: pf#d6
got message: qSupported#37
got message: qfThreadInfo#bb
got message: qsThreadInfo#c8
got message: g#67
got message: Z0,6c,4#af
`

The last of these is the important one; according to [here](https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#Packets), the `Z0` command should insert a software breakpoint at the address of the second argument (hex `6c`) of type `4` (which in ARM is a 32bit ARM mode breakpoint). Tracing through the mgba binary itself, the `ARMDebuggerSetSoftwareBreakpoint` is hit with the correct arguments, and a breakpoint struct is added to the `swBreakpoints` list. It doesn't appear to have any code here to patch the BKPT instruction into the code, and I'm having trouble finding it.

According to IDA, the ARM code looks something like this:
`
address: instruction
0x00: B 0x68
...
0x68: CMP ...
0x6C: MOVEQ ...  < breakpoint here
0x70: MOV ...
0x74: LDRB ...
`

Using a debugger for the mgba binary, I put a breakpoint on line 81 of `src/debugger/debugger.c`, which is the `DEBUGGER_CUSTOM` case in the `mDebuggerRun` function. Tracing through the mgba binary, the instructions run by the emulator in order are

`
B ...
CMP ...
MOVEQ ... < breakpoint should occur here, should this be a BKPT instruction ?
`

By continuing to step through the `mDebuggerRun` function after the `MOVEQ` instruction is executed, it then calls line 82 of `src/debugger/debugger.c`: `debugger->platform->checkBreakpoints(debugger->platform);` which really maps to `ARMDebuggerCheckBreakpoints` in `src/arm/debugger/debugger.c` according to the debugger. As noted before, this function calls `_lookupBreakpoint(&debugger->breakpoints, ...)` which only checks for hardware breakpoints, not software ones. It returns immediately because there are no hardware breakpoints.

Finally, the `mDebuggerRun` function calls `debugger->custom(...)`, that maps to `_gdbStubPoll`, and which returns immediately because there is no polling to perform.

The main loop then starts again, and the `MOV` instruction is decoded, then `LDRB` and so forth.

If a BKPT instruction was present, it looks like it would then call the `GBABreakpoint` function, which eventually performs the correct call to `mDebuggerEnter(..., DEBUGGER_ENTER_BREAKPOINT, ...)`

So my current issue is: where in the codebase is the BKPT instruction patched into the ARM memory?

**Comment by endrift** [comment]
Ah, I forgot to mention that there are a few regions of memory where software breakpoints don't work due to them being readonly in the emulator, and thus not able to be patched. The BIOS is the big one. It would take some major reworking to get that working, as I'd need to manage a copy of the BIOS separate from the master copy. I just recommend using a hardware breakpoint for BIOS.

**Comment by jeremyherbert** [comment]
Yep, that looks like it. Thanks for the help. Closing this
